"use client"

import { ThemeProvider } from "@/providers/ThemeProvider";

export default function Home() {
  return (
    <ThemeProvider
      defaultButtonVariant="text-stagger"
      defaultTextAnimation="entrance-slide"
      borderRadius="rounded"
    >
      <div className="min-h-screen">
        <div className="text-center py-16">
          <h1 className="text-4xl font-bold mb-4">Welcome to Webild Components</h1>
          <p className="text-lg text-gray-600">This is a chat model response, generated by Mistral AI. If you have any questions or feedback, please let me know!</p>
        </div>
      </div>
    </ThemeProvider>
  );
}